export const messages = {
    validObjectId: 'Enter valid object ID',
    //auth
    webInfo: 'Web info fetch successfully',
    loginSuccess: 'login successfully',
    loginOnAnotherDevice: 'Your account has logged in on another device',
    blockByAdmin: 'Your account has been blocked by admin',
    userNotFound: 'User not found',
    tokenRequired: 'Token required',
    profileFetch: 'Profile fetch successfully',
    fileUploadSuccess: 'File uploaded successfully',
    selectFile: 'Please select a file to upload',
    orderPlaced: 'Order placed successfully',
    orderCheck: 'Order price fetch successfully',
    wrongPromo: 'Enter valid promo code',
    cartEmpty: 'Provide alteast one product',
    ordersFetch: 'Order fetch successfully',
    ordersDelete: 'Order deleted successfully',
    viewAddress: 'Address fetch successfully',
    addressUpdated: 'Address updated successfully',
    promoPurchased: 'Promo purchased successfully',
    orderNotFound: 'Order not found',
    orderStatus: 'Order status updated successfully',
    promoStatus: 'Promo status',
    promoNotFound: 'Promo not found',
    promoFetch: 'Promo offer fetch successfully',
    contactSuccess: 'Contact successfully',
    completeAddress: 'Complete address details first.',
    //admin
    invalidEmailAndPassword: 'Please enter valid email address and password',
    forgotPasswordLinkSent: 'A forgot password link has been sent on your mail',
    emailNotRegistered: 'Email is not register with us',
    linkFetched: 'Link checked',
    linkExpired: 'Link expired',
    passwordChanged: 'Password updated',
    incorrectOldPassword: 'Please enter correct Old Password',
    mailNotSent: 'Mail not sent, Try again',
    passwordHasUpdated: 'Your password has been updated. Please login again',
    dashboardFetched: 'Dashboard fetch successfully',
    userListFetched: 'User fetch successfully',
    userDetailsUpdated: 'User details updated',
    userUnblocked: 'User unblocked successfully',
    userBlocked: 'User blocked successfully',
    enterValidEmail: 'Please enter valid email address',
    //content
    contentUpdate: 'Content updated successfully',
    contentNotFound: 'Content not found',
    contentFetch: 'Content fetch successfully',
    faqFetch: 'FAQ fetch successfully',
    faqNotFound: 'FAQ not found',
    faqUpdate: 'FAQ updated successfully',
    faqAdd: 'FAQ added successfully',
    faqRemove: 'FAQ removed successfully',
    //discount
    discountUpdate: 'Discount details updated successfully',
    discountNotFound: 'Discount details not found',
    discountFetch: 'Discount details fetch successfully',
    //homepage
    homepageUpdate: 'Homepage details updated successfully',
    homepageNotFound: 'Homepage details not found',
    homepageFetch: 'Homepage details fetch successfully',
    testimonialFetch: 'Testimonial fetch successfully',
    testimonialNotFound: 'Testimonial not found',
    testimonialUpdate: 'Testimonial updated successfully',
    testimonialAdd: 'Testimonial added successfully',
    testimonialRemove: 'Testimonial removed successfully',

    //otp
    otpSent: 'OTP sent successfully',
    otpNotMatch: 'Wrong OTP',
    otpVerify: 'OTP verified successfully',
    popupFetch : 'Popup data fetch',
    popupNotFound : 'Data not found',
    popupUpdate : "Data Updated"
}
